### ISSUE TITLE
Ease of adding a new task

### ISSUE THREAD

**Issue by YashBhalodi** [DrashtiG/Work_Record#3]
Just an improvement suggestion.

After writing a task description in `taskText`, pressing `Enter` should add the task to the to-do list, instead of having to click the "ADD TASK" button manually each time.

A Solution: using `keypress`
```
$("#taskText").keypress(function(event) { 
            if (event.keyCode === 13) { 
                $("#addTask").click(); 
            } 
        });
```

**Comment by DrashtiG** [comment]
@YashBhalodi That's a good idea! Thanks for suggestion will make the required changes.
